# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36ea1a77bb7880efaee59651b615477b8777ac71c52c9aaf651b74b4713068602c4212a061d0e56095376498bc6be0c053459b5b53e02396bd506fa61c4f418d

test:
  secret_key_base: de57fcbed258accc6fe7b493036b693ddcfb1d057e5feb9386feb4b854cd0f93d86bf17bfe9bbd1d2397d44d6bb9f27f3c282d9a110941a036e5c33470857bcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
